# -*- coding: utf-8 -*-
"""Chương6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbQpK-9-dh4M-h1VWvPq9dtYlxbnGnw7
"""

#Câu1:
from random import randrange
print("Chương trình xử lý List")
n=int(input("Nhập số phần tử"))
lst=[0]*n
for i in range(n):
 lst[i]=randrange(-100,100)
print("List ngẫu nhiên là:")
print(lst)
print("Mời bạn thêm số mới:")
value=int(input())
lst.append(value)
print(lst)
print("bạn muốn đếm số nào:")
k=int(input())
dem=lst.count(k)
print(k,"xuất hiện ",dem,"trong list")
def CheckPrime(n):
    d=0
    for i in range(1,n+1):
     if n%i ==0:
      d+=1
     return d==2
demnt=0
tongnt=0
for x in lst:
 if CheckPrime(x):
  demnt+=1
 tongnt+=x
print("Có ",demnt,"số nguyên tố trong list")
print("Tổng=",tongnt)
lst.sort()
print("List sau khi sort:")
print(lst)
del lst
print("List sau khi xóa:")
print(lst)

#Câu2:
from random import randrange
lst=[]
print("Nhập số phần tử:")
n=int(input())
for i in range(n):
 lst.append(randrange(0,100))
print("List sau khi tạo ngẫu nhiên là:")
print(lst)
x=int(input("Mời bạn chèn thêm số mới"))
lst.append(x)
print("List sau khi chèn:")
print(lst)
k=int(input("Mời nhập số để xóa"))
while lst.count(k)>0:
 lst.remove(k)
print("List sau khi xóa:")
print(lst)
def CheckDoiXung(lst):
 for i in range(len(lst)):
  if lst[i]!=lst[len(lst)-i-1]:
   return False
 return True
kt=CheckDoiXung(lst)
if kt==True:
 print("List đối xứng")
else:
 print("List không đối xứng")

#Câu4:
"""
(a) lst[0] = 3
(b) lst[3] = 5
(c) lst[x] = lst[2] = 1
(d) lst[-x] = lst[-2] = 5
(e) lst[x+1] = lst[3] = 5
(f) lst[x] + 1 = 1 + 1 = 2
(g) lst[lst[x]] = lst[1] = 0
(h) lst[lst[lst[x]]] = lst[0] = 3
"""

#Câu5:
"""
(a) lst → [20, 1, -34, 40, -8, 60, 1, 3]
(b) lst[0:3] → [20, 1, -34]
(c) lst[4:8] → [-8, 60, 1, 3]
(d) lst[4:33] → [-8, 60, 1, 3]
(e) lst[-5:-3] → [40, -8]
(f) lst[22:3] → []
(g) lst[4:] → [-8, 60, 1, 3]
(h) lst[:3] → [20, 1, -34]
(i) lst[:4] → [20, 1, -34, 40]
(j) lst[1:5] → [1, -34, 40, -8]
(k) -34 in lst → True
(l) -34 not in lst → False
(m) len(lst) → 8 ✅
"""

#Câu6:
import random

N = int(input("Nhập số lượng phần tử N: "))
lst = random.sample(range(1, 100), N)  # tạo N số ngẫu nhiên không trùng nhau từ 1..100
print("List ngẫu nhiên:", lst)

#Câu7:
n = int(input("Nhập số lượng phần tử: "))
lst = []

for i in range(n):
    while True:
        x = int(input(f"Nhập phần tử thứ {i}: "))
        if i == 0 or x > lst[-1]:  # phải lớn hơn phần tử trước
            lst.append(x)
            break
        else:
            print("Sai thứ tự tăng! Nhập lại.")

print("Dãy sau khi nhập xong:", lst)

#Câu8:
n = int(input("Nhập số lượng phần tử: "))
M = []

for i in range(n):
    x = float(input(f"Nhập M[{i}]: "))
    M.append(x)

M.sort(reverse=True)  # sắp xếp giảm dần
print("Dãy sau khi sắp xếp giảm dần:", M)

#Câu9:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Nhập mảng
M = [3, 6, 7, 8, 11, 17, 2, 90, 2, 5, 4, 5, 8]

# Số lẻ
odd = [x for x in M if x % 2 == 1]
print("Số lẻ:", odd, "→ Có", len(odd), "số lẻ")

# Số chẵn
even = [x for x in M if x % 2 == 0]
print("Số chẵn:", even, "→ Có", len(even), "số chẵn")

# Số nguyên tố
prime = [x for x in M if is_prime(x)]
print("Nguyên tố:", prime)

# Không phải nguyên tố
not_prime = [x for x in M if not is_prime(x)]
print("Không nguyên tố:", not_prime)

#câu10:
def nhap_ma_tran(ten):
    m = int(input(f"Nhập số dòng của ma trận {ten}: "))
    n = int(input(f"Nhập số cột của ma trận {ten}: "))
    print(f"Nhập các phần tử cho ma trận {ten}:")
    mat = []
    for i in range(m):
        hang = list(map(int, input().split()))
        mat.append(hang)
    return mat

def in_ma_tran(mat, ten):
    print(f"Ma trận {ten}:")
    for hang in mat:
        print(*hang)

def cong_ma_tran(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        print("Không thể cộng 2 ma trận khác kích thước.")
        return None
    m, n = len(A), len(A[0])
    C = [[A[i][j] + B[i][j] for j in range(n)] for i in range(m)]
    return C

def hoan_vi(mat):
    m, n = len(mat), len(mat[0])
    T = [[mat[j][i] for j in range(m)] for i in range(n)]
    return T


# --- Chạy chương trình ---
A = nhap_ma_tran("A")
B = nhap_ma_tran("B")

in_ma_tran(A, "A")
in_ma_tran(B, "B")

C = cong_ma_tran(A, B)
if C:
    in_ma_tran(C, "A + B")

AT = hoan_vi(A)
BT = hoan_vi(B)

in_ma_tran(AT, "A^T")
in_ma_tran(BT, "B^T")

#Câu 3:
from random import randrange
def TaoMaTran(m,n):
 D=[]
 for i in range(m):
  row=[]
 for j in range(n):
  row.append(randrange(100))
 D.append(row)
 return D
def XuatMaTran(D):
 for row in D:
  for element in row:
   print(element,end='\t')
 print()
def LayDong(r):
 R=D[r]
 return R
def XuatList1Chieu(R):
 for element in R:
  print(element,end='\t')
def LayCot(c):
 C=[]
 for i in range(len(D)):
  C.append(D[i][c])
 return C
def MAX(D):
 max=D[0][0]
 for i in range(len(D)):
  for j in range(len(D[i])):
   if(max<D[i][j]):
    max=D[i][j]
 return max
print("Nhập số dòng:")
m=int(input())
print("Nhập số cột:")
n=int(input())
D=TaoMaTran(m,n)
XuatMaTran(D)
print("Mời bạn nhập dòng muốn xuất:")
r=int(input())
XuatList1Chieu(LayDong(r))
print("Mời bạn nhập cột muốn xuất:")
c=int(input())
XuatList1Chieu(LayCot(c))
max=MAX(D)
print("Số lớn nhất trong ma trận=",max)